### ISSUE TITLE
Merge redundant board entry?

### ISSUE THREAD

**Issue by jcstaudt** [armbian/testings#145]
How is **lime-a64** different than **olinuxino-a64**?

I own an A64-OLinuXino and am able to boot just fine using the image(s) provided on the official download page. Upon running ``createreport.sh`` on the board, the output even says ``lime-a64-next.report``. Am I confused? If not, should we either (a) rename the existing entries a64-olinuxino, etc, or (b) remove the a64-olinuxino entries altogether in order to reduce the list of missing board reports?

**Comment by igorpecovnik** [comment]
They are the same. We use our own naming in some cases so yes its a bit confusing. We are wrong with older Olimex boards as well, so I guess changing one to wrong is better than correcting others.

**Comment by jcstaudt** [comment]
I don't mind fixing the wrong entries; I would just need some guidance. If someone walks me through the steps to correct one board, I'm willing to correct the rest.

**Comment by igorpecovnik** [comment]
Removing a64-olinuxino entries if they still exists anywhere ... I removed duplicate in a build config some time ago. This testing tool is anyway generic for naming so we should close the issue here.
